version: "3"

services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/code
    tty: true
    command: >
      bash -c "pip install -r requirements.txt --no-cache-dir &&
      python3 app.py"
    env_file: ./app.env
